import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
const __filename=fileURLToPath(import.meta.url), __dirname=path.dirname(__filename);
const app=express(), PORT=process.env.PORT||10000, PASS=process.env.ADMIN_PASSWORD||'admin12345';
app.use(express.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname,'public')));
const demoProducts=[
{id:1,name:'Luna Velvet Sofa',category:'Sofa',price:48500,oldPrice:54900,rating:4.9,reviews:84,stock:8,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=88',featured:true,material:'Premium fabric with solid wood frame'},
{id:2,name:'Regal 6-Seater Dining Set',category:'Dining',price:72500,oldPrice:79900,rating:4.8,reviews:61,stock:5,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=88',featured:true,material:'Engineered wood with premium finish'},
{id:3,name:'Elysian King Bed',category:'Bedroom',price:58900,oldPrice:64900,rating:4.9,reviews:72,stock:6,image:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=88',featured:true,material:'Solid wood and upholstered headboard'},
{id:4,name:'Aura Lounge Chair',category:'Chair',price:16800,oldPrice:19500,rating:4.7,reviews:39,stock:14,image:'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1000&q=88',featured:false,material:'Premium fabric with ash wood legs'},
{id:5,name:'Majesty L-Shape Sofa',category:'Sofa',price:69900,oldPrice:78900,rating:5,reviews:55,stock:4,image:'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1000&q=88',featured:true,material:'Performance fabric and solid frame'},
{id:6,name:'Noble Office Desk',category:'Office',price:17900,oldPrice:20900,rating:4.8,reviews:28,stock:17,image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=88',featured:false,material:'Oak-tone top with steel base'},
{id:7,name:'Verona Side Table',category:'Table',price:9800,oldPrice:11900,rating:4.8,reviews:31,stock:12,image:'https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=1000&q=88',featured:false,material:'Solid wood with premium polish'},
{id:8,name:'Opal Accent Table',category:'Table',price:7900,oldPrice:8900,rating:4.6,reviews:22,stock:21,image:'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1000&q=88',featured:false,material:'Wood finish with minimalist profile'}];
const demoReviews=[
{id:1,name:'Nusrat Jahan',rating:5,text:'Sofa ta exactly picture-er moto. Finish and comfort duita-i excellent.',product:'Luna Velvet Sofa',verified:true},
{id:2,name:'Tanvir Ahmed',rating:5,text:'Dining set-er quality dekhe really impressed. Delivery o on-time chilo.',product:'Regal 6-Seater Dining Set',verified:true},
{id:3,name:'Mim Akter',rating:4.9,text:'Bedroom ta completely transform hoye geche. Looks very premium.',product:'Elysian King Bed',verified:true},
{id:4,name:'Rafiul Islam',rating:4.8,text:'Customer service helpful chilo. Packaging strong and neat.',product:'Majesty L-Shape Sofa',verified:true},
{id:5,name:'Sadia Rahman',rating:4.9,text:'Office desk ta stylish and solid. Highly recommended.',product:'Noble Office Desk',verified:true},
{id:6,name:'Arif Hossain',rating:5,text:'Website theke order kora easy, product quality-o excellent.',product:'Aura Lounge Chair',verified:true}];
const mem={products:structuredClone(demoProducts),reviews:structuredClone(demoReviews),orders:[],settings:{whatsapp:'+8801734387115',facebook:'#',instagram:'#',youtube:'#',tiktok:'#',delivery:'Dhaka 2–4 days • All Bangladesh 3–7 days'}};
let pool=null;if(process.env.DATABASE_URL) pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price NUMERIC NOT NULL,old_price NUMERIC,rating NUMERIC DEFAULT 5,reviews INTEGER DEFAULT 0,stock INTEGER DEFAULT 0,image TEXT,featured BOOLEAN DEFAULT FALSE,material TEXT);CREATE TABLE IF NOT EXISTS reviews(id SERIAL PRIMARY KEY,name TEXT NOT NULL,rating NUMERIC NOT NULL,text TEXT NOT NULL,product TEXT,verified BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,order_no TEXT UNIQUE NOT NULL,customer JSONB NOT NULL,items JSONB NOT NULL,total NUMERIC NOT NULL,status TEXT DEFAULT 'Pending',payment TEXT,created_at TIMESTAMP DEFAULT NOW());`);const c=await pool.query('SELECT COUNT(*)::int c FROM products');if(c.rows[0].c===0)for(const p of demoProducts)await pool.query('INSERT INTO products(id,name,category,price,old_price,rating,reviews,stock,image,featured,material) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO NOTHING',[p.id,p.name,p.category,p.price,p.oldPrice,p.rating,p.reviews,p.stock,p.image,p.featured,p.material]);}
const auth=(req,res,next)=>req.headers['x-admin-password']===PASS?next():res.status(401).json({error:'Unauthorized'});
const listProducts=async()=>pool?(await pool.query('SELECT id,name,category,price,old_price "oldPrice",rating,reviews,stock,image,featured,material FROM products ORDER BY id DESC')).rows:mem.products;
const listReviews=async()=>pool?(await pool.query('SELECT id,name,rating,text,product,verified FROM reviews ORDER BY created_at DESC')).rows:mem.reviews;
app.get('/api/products',async(_,r)=>{try{r.json(await listProducts())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/reviews',async(_,r)=>{try{r.json(await listReviews())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/settings',(_,r)=>r.json(mem.settings));
app.post('/api/reviews',async(q,r)=>{const {name,rating,text,product}=q.body;if(!name||!text||!rating)return r.status(400).json({error:'Required fields'});try{if(!pool){const x={id:Date.now(),name,rating:Number(rating),text,product:product||'',verified:false};mem.reviews.unshift(x);return r.json(x)}const x=await pool.query('INSERT INTO reviews(name,rating,text,product,verified) VALUES($1,$2,$3,$4,false) RETURNING id,name,rating,text,product,verified',[name,rating,text,product||'']);r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/orders',async(q,r)=>{const {customer,items,total,payment}=q.body;if(!customer?.name||!customer?.phone||!customer?.address||!items?.length)return r.status(400).json({error:'Customer details required'});const no='MBD'+Date.now().toString().slice(-9);try{if(!pool){mem.orders.unshift({orderNo:no,customer,items,total,payment,status:'Pending'});return r.json({orderNo:no,status:'Pending'})}await pool.query('INSERT INTO orders(order_no,customer,items,total,status,payment) VALUES($1,$2,$3,$4,\'Pending\',$5)',[no,JSON.stringify(customer),JSON.stringify(items),total,payment||'Cash on Delivery']);r.json({orderNo:no,status:'Pending'})}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/orders/:no',async(q,r)=>{try{if(!pool){const o=mem.orders.find(x=>x.orderNo===q.params.no);return o?r.json(o):r.status(404).json({error:'Order not found'})}const x=await pool.query('SELECT order_no "orderNo",customer,items,total,status,payment,created_at "createdAt" FROM orders WHERE order_no=$1',[q.params.no]);if(!x.rowCount)return r.status(404).json({error:'Order not found'});r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/admin/login',(q,r)=>r.json({ok:q.body.password===PASS}));
app.get('/api/admin/orders',auth,async(_,r)=>{try{r.json(pool?(await pool.query('SELECT order_no "orderNo",customer,items,total,status,payment,created_at "createdAt" FROM orders ORDER BY created_at DESC')).rows:mem.orders)}catch(e){r.status(500).json({error:e.message})}});
app.patch('/api/admin/orders/:no',auth,async(q,r)=>{try{if(!pool){const o=mem.orders.find(x=>x.orderNo===q.params.no);if(!o)return r.status(404).json({error:'Not found'});o.status=q.body.status;return r.json(o)}const x=await pool.query('UPDATE orders SET status=$1 WHERE order_no=$2 RETURNING order_no "orderNo",status',[q.body.status,q.params.no]);r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/products',auth,async(q,r)=>{const p=q.body;try{if(!pool){const id=Math.max(...mem.products.map(x=>x.id))+1;const x={...p,id};mem.products.push(x);return r.json(x)}const x=await pool.query('INSERT INTO products(name,category,price,old_price,rating,reviews,stock,image,featured,material) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[p.name,p.category,p.price,p.oldPrice||null,p.rating||5,p.reviews||0,p.stock||0,p.image||'',!!p.featured,p.material||'']);r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.put('/api/products/:id',auth,async(q,r)=>{const p=q.body,id=Number(q.params.id);try{if(!pool){const i=mem.products.findIndex(x=>x.id===id);if(i<0)return r.status(404).json({error:'Not found'});mem.products[i]={...mem.products[i],...p,id};return r.json(mem.products[i])}const x=await pool.query('UPDATE products SET name=$1,category=$2,price=$3,old_price=$4,rating=$5,reviews=$6,stock=$7,image=$8,featured=$9,material=$10 WHERE id=$11 RETURNING *',[p.name,p.category,p.price,p.oldPrice||null,p.rating||5,p.reviews||0,p.stock||0,p.image||'',!!p.featured,p.material||'',id]);r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.delete('/api/products/:id',auth,async(q,r)=>{const id=Number(q.params.id);try{if(!pool){mem.products=mem.products.filter(x=>x.id!==id);return r.json({ok:true})}await pool.query('DELETE FROM products WHERE id=$1',[id]);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.delete('/api/reviews/:id',auth,async(q,r)=>{const id=Number(q.params.id);try{if(!pool){mem.reviews=mem.reviews.filter(x=>x.id!==id);return r.json({ok:true})}await pool.query('DELETE FROM reviews WHERE id=$1',[id]);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.put('/api/settings',auth,(q,r)=>{Object.assign(mem.settings,q.body);r.json(mem.settings)});
app.use((req,res,next)=>req.method==='GET'&&!req.path.startsWith('/api/')?res.sendFile(path.join(__dirname,'public','index.html')):next());
app.use((_,r)=>r.status(404).json({error:'Not found'}));
initDb().catch(e=>console.error('DB init:',e.message));
app.listen(PORT,()=>console.log(`Ma Babar Doya Furniture running on ${PORT}`));
