const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DATA=path.join(ROOT,'data','data.json');
let db=JSON.parse(fs.readFileSync(DATA,'utf8')); const sessions=new Map();
function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ttg_session='))?.split('=')[1]}
function admin(req){const t=cookie(req);return t&&sessions.get(t)?.admin}
function session(res){const t=crypto.randomBytes(24).toString('hex');sessions.set(t,{admin:true});res.setHeader('Set-Cookie',`ttg_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400`)}
function orderId(){return 'TTG-'+String(db.orders.length+1).padStart(6,'0')}
function staticFile(req,res,url){let p=url.pathname==='/'?'/index.html':url.pathname==='/admin'||url.pathname==='/admin/'||url.pathname==='/admin.html'?'/admin.html':url.pathname; p=path.normalize(p).replace(/^\.\.(\/|\\)/,'');const f=path.join(PUBLIC,p);if(!f.startsWith(PUBLIC)){res.writeHead(403);return res.end()}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f);const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(b)})}
async function api(req,res,u){
 try{
  if(req.method==='GET'&&u.pathname==='/api/store')return json(res,200,{settings:db.settings,categories:db.categories,products:db.products,reviews:db.reviews,faqs:db.faqs});
  if(req.method==='POST'&&u.pathname==='/api/admin/login'){const b=await body(req);if(b.password===db.adminPassword){session(res);return json(res,200,{ok:true})}return json(res,401,{error:'Invalid password'})}
  if(req.method==='POST'&&u.pathname==='/api/orders'){const b=await body(req);if(!b.customer||!b.items?.length)return json(res,400,{error:'Missing order details'});const o={id:orderId(),createdAt:new Date().toISOString(),status:'Pending',customer:b.customer,items:b.items,total:b.total||0};db.orders.push(o);save();return json(res,201,{ok:true,order:o})}
  if(req.method==='POST'&&u.pathname==='/api/chat'){const b=await body(req);const q=String(b.message||'').toLowerCase();let ps=db.products.filter(p=>p.stock>0);const colors=['maroon','red','black','cream','white','blue','green','mustard','gold','olive'];const foundColor=colors.find(c=>q.includes(c));if(foundColor)ps=ps.filter(p=>p.colors.some(c=>c.toLowerCase().includes(foundColor)));const cats=db.categories.map(c=>c.name);const foundCat=cats.find(c=>q.includes(c.toLowerCase()));if(foundCat)ps=ps.filter(p=>p.category===foundCat);const nums=q.match(/\d{3,6}/g)?.map(Number)||[];if(nums.length){const max=Math.max(...nums);if(/under|within|budget|less|below|up to|moddhe/i.test(q))ps=ps.filter(p=>p.price<=max)}let text='';if(/hello|hi|assalamu|hey/.test(q))text='Hello! Welcome to Tangail Tath Ghor. আপনি কী খুঁজছেন—saree, panjabi, fabric, shawl, stole নাকি অন্য কিছু?';else if(/delivery|shipping|কত দিন|কতদিন/.test(q))text=`Delivery সাধারণত 2–5 working days. ৳${db.settings.freeShippingThreshold} বা তার বেশি অর্ডারে free shipping available.`;else if(/payment|bkash|nagad|rocket|cod|cash/.test(q))text='Cash on Delivery, bKash, Nagad এবং Rocket payment available.';else if(/order|buy|কিনব|অর্ডার/.test(q))text='অবশ্যই। Product পছন্দ হলে “Order Now” চাপুন অথবা আমাকে product-এর নাম বলুন—আমি order details নিতে সাহায্য করব।';else if(/kemon|good|review|ভালো|কেমন/.test(q))text='এই collection-এর quality ও traditional look-এর feedback ভালো। কোন product-টা জানতে চাইছেন? নামটা বললে আমি details দেখাতে পারি।';else text=ps.length?`আপনার জন্য ${Math.min(ps.length,4)}টি matching product পেয়েছি। নিচে দেখুন।`:'এই মুহূর্তে matching product পাইনি। অন্য category, color বা budget দিয়ে চেষ্টা করুন।';return json(res,200,{text,products:ps.slice(0,4)});}
  if(!admin(req))return json(res,401,{error:'Unauthorized'});
  if(req.method==='GET'&&u.pathname==='/api/admin/data')return json(res,200,{settings:db.settings,categories:db.categories,products:db.products,reviews:db.reviews,faqs:db.faqs,orders:db.orders});
  if(req.method==='POST'&&u.pathname==='/api/admin/settings'){const b=await body(req);db.settings={...db.settings,...b};save();return json(res,200,{ok:true,settings:db.settings})}
  if(req.method==='POST'&&u.pathname==='/api/admin/change-password'){const b=await body(req);if(!b.password||b.password.length<8)return json(res,400,{error:'Password must be at least 8 characters'});db.adminPassword=b.password;save();return json(res,200,{ok:true})}
  if(req.method==='POST'&&u.pathname==='/api/admin/products'){const b=await body(req);if(!b.name||!b.price)return json(res,400,{error:'Name and price required'});const p={...b,id:b.id||('P'+crypto.randomBytes(4).toString('hex')),stock:Number(b.stock||0),price:Number(b.price),oldPrice:Number(b.oldPrice||0)};const i=db.products.findIndex(x=>x.id===p.id);if(i>=0)db.products[i]=p;else db.products.push(p);save();return json(res,200,{ok:true,product:p})}
  if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/products/')){const id=u.pathname.split('/').pop();db.products=db.products.filter(p=>p.id!==id);save();return json(res,200,{ok:true})}
  if(req.method==='POST'&&u.pathname==='/api/admin/categories'){const b=await body(req);const c={...b,id:b.id||('C'+crypto.randomBytes(4).toString('hex'))};const i=db.categories.findIndex(x=>x.id===c.id);if(i>=0)db.categories[i]=c;else db.categories.push(c);save();return json(res,200,{ok:true,category:c})}
  if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/categories/')){const id=u.pathname.split('/').pop();db.categories=db.categories.filter(c=>c.id!==id);save();return json(res,200,{ok:true})}
  if(req.method==='POST'&&u.pathname==='/api/admin/reviews'){const b=await body(req);const r={...b,id:b.id||('R'+crypto.randomBytes(4).toString('hex'))};const i=db.reviews.findIndex(x=>x.id===r.id);if(i>=0)db.reviews[i]=r;else db.reviews.push(r);save();return json(res,200,{ok:true})}
  if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/reviews/')){const id=u.pathname.split('/').pop();db.reviews=db.reviews.filter(x=>x.id!==id);save();return json(res,200,{ok:true})}
  if(req.method==='POST'&&u.pathname==='/api/admin/faqs'){const b=await body(req);const f={...b,id:b.id||('F'+crypto.randomBytes(4).toString('hex'))};const i=db.faqs.findIndex(x=>x.id===f.id);if(i>=0)db.faqs[i]=f;else db.faqs.push(f);save();return json(res,200,{ok:true})}
  if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/faqs/')){const id=u.pathname.split('/').pop();db.faqs=db.faqs.filter(x=>x.id!==id);save();return json(res,200,{ok:true})}
  if(req.method==='POST'&&u.pathname.startsWith('/api/admin/orders/')){const id=u.pathname.split('/').pop();const b=await body(req);const o=db.orders.find(x=>x.id===id);if(!o)return json(res,404,{error:'Order not found'});o.status=b.status||o.status;save();return json(res,200,{ok:true,order:o})}
  return json(res,404,{error:'Not found'});
 }catch(e){console.error(e);return json(res,500,{error:'Server error'})}
}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/'))return api(req,res,u);staticFile(req,res,u)});
const port=process.env.PORT||10000;server.listen(port,()=>console.log(`Tangail Tath Ghor running on ${port}`));
